using EmployeeOnboarding.Api.Configuration;
using Microsoft.Extensions.Options;

namespace EmployeeOnboarding.Api.Services;

/// <summary>
/// File-system backed document storage used for local development and automated
/// tests. Files are written under a non-public application data folder and the
/// stored name is generated by the server so user input never controls the path
/// (User Story 2791).
/// </summary>
public class LocalDocumentStorage : IDocumentStorage
{
    private readonly string _root;
    private readonly ILogger<LocalDocumentStorage> _logger;

    public LocalDocumentStorage(IOptions<OnboardingOptions> options, ILogger<LocalDocumentStorage> logger)
    {
        _logger = logger;
        var configured = options.Value.LocalDocumentStorageRoot;
        _root = Path.IsPathRooted(configured)
            ? configured
            : Path.Combine(AppContext.BaseDirectory, configured);
        Directory.CreateDirectory(_root);
    }

    public async Task<string> SaveAsync(Guid onboardingRecordId, string fileName, Stream content, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(content);

        var extension = Path.GetExtension(fileName);
        if (extension.Length > 10)
        {
            extension = extension[..10];
        }

        var folder = Path.Combine(_root, onboardingRecordId.ToString("N"));
        Directory.CreateDirectory(folder);

        var safeName = string.Concat(Guid.NewGuid().ToString("N"), extension);
        var fullPath = Path.Combine(folder, safeName);

        await using (var target = File.Create(fullPath))
        {
            await content.CopyToAsync(target, cancellationToken);
        }

        var relativePath = Path.Combine(onboardingRecordId.ToString("N"), safeName).Replace('\\', '/');
        _logger.LogInformation("Stored onboarding document for record {RecordId} at {RelativePath}", onboardingRecordId, relativePath);
        return relativePath;
    }

    public Task<Stream?> OpenReadAsync(string storagePath, CancellationToken cancellationToken = default)
    {
        var fullPath = ResolvePath(storagePath);
        if (fullPath is null || !File.Exists(fullPath))
        {
            return Task.FromResult<Stream?>(null);
        }

        Stream stream = File.OpenRead(fullPath);
        return Task.FromResult<Stream?>(stream);
    }

    public Task<bool> DeleteAsync(string storagePath, CancellationToken cancellationToken = default)
    {
        var fullPath = ResolvePath(storagePath);
        if (fullPath is null || !File.Exists(fullPath))
        {
            return Task.FromResult(false);
        }

        File.Delete(fullPath);
        return Task.FromResult(true);
    }

    private string? ResolvePath(string storagePath)
    {
        if (string.IsNullOrWhiteSpace(storagePath))
        {
            return null;
        }

        var candidate = Path.GetFullPath(Path.Combine(_root, storagePath));
        var rootFull = Path.GetFullPath(_root);
        return candidate.StartsWith(rootFull, StringComparison.Ordinal) ? candidate : null;
    }
}
